# -*- mode: org; fill-column: 79; -*-

#+TITLE: Working With Static Sites
#+SUBTITLE: Bringing the Power of Simplicity to Modern Sites
#+AUTHOR: Raymond Camden
#+SUBAUTHOR: Brian Rinaldo
#+DATE: February 28, 2017
#+MACRO: VERSION 0.1.0
#+MACRO: EDITION 0.1

#+texinfo: @insertcopying

* Preface
  :PROPERTIES:
  :unnumbered: t
  :END:
  Because of the *benefits* static site generators offer, static sites
  generators are used to run thousands of sites and are becoming the basis for
  a broad *set of tools* that reach the casual developer and the nontechnical
  content writer.

  It can be difficult to know which tools to choose and how to get started.

  *That is the problem the authors hope to address in writing this book.*  By
   providing *common scenarios* and insights on how to address them, the
   authors hope to make it easier for anyone to create static sites solutions
   and take advantage of the speed, flexibilty, and security they offer.

** What You Need to Know

*** Who this book is for
    - This book is for web developers who are looking for a simpler way to
      build and deploy websites.
    - For developers with experience with dynamic app servers (like PHP,
      Node.js, and ColdFusion), this book will present a simpler alternative.
    - For developers who are still working with simple websites but need a way
      to make them more powerful.
*** What's not covered
    - This book focuses on static site generators that work from the command
      line.
    - Desktop tools that have similar features are not covered.
*** How this book is organized
    - Begins by describing why you would want to use static sites.
    - Subsequent chapters focus on a specific type of site and uses this as a
      way of introducing different static site generators.
    - How to build a site
    - More advanced topics, such as adding dynamic elements back in,
    - Working with CMS
    - How to deploy and host a site
    - How to migrate from a dynamic site to a static one
** Conventions
   - /Italic/ :: Indicates new terms, URLs, email addresses, filenames, and
                 file extensions
   - ~Constant Width~ :: Used for program listings, as well as within
        paragraphs to refer to program elements such as variables or function
        names, databases, data types, environment variables, statements, and
        keywords
   - {{{command(Command)}}} :: Shows commands or other text that should be
        typed literally by the user
   - {{{samp(Sample)}}} :: Shows text that should be replaced with
        user-supplied values or by values determined by context.
** Code Examples
   Supplemental material (code examples, exercises, etc.) is available for
   download at [[https://github.com/cfjedimaster/Static-Sites-Book]]
* Why Static Sites
  Why would static sites be a worthwhile option for today's web?  This chapter
  will explore some of the benefits of static sites before diving into how the
  changing technology behind static sites (i.e., static site generators---the
  topic of this book) are making them viable again.

** Benefits of Static Sites
   Of the many reasons that static sites are coming back into fashion, two
   stand out:

   1. Static sites are /fast/
   2. Statis sites are /secure/

** Static Sites are /Fast/
   #+cindex: performance, website
   #+cindex: website performance
   #+cindex: abandon, webiste loading
   Website performance is critical.  Users tend to abandon sites that take
   longer than three seconds to load (with a load time of under two seconds
   being considered optimal for mobile).  Achieving this level of website
   performance can be difficult.

   #+cindex: bottlenecks, webiste loading
   #+cindex: server-side rendering, bottleneck
   #+cindex: cache, website
   #+cindex: Content Delivery Network (CDN)
   #+cindex: CDN
   #+cindex: dynamic rendering, bottleneck
   #+cindex: points of failure, website loading
   By their very nature, static sites load extremely fast.  This is because
   every visitor is served the exact same HTML without the bottlenecks caused
   by a server-side language, database, or any kind of dynamic rendering.
   Plus, static sites are extremely easy to cache and serve via a content
   delivery network (CDN), making  them even faster for the end user.  In
   addition, once you eliminate dynamic rendering from a database, you've
   eliminated numerous points of failure that often cause sites to be
   unresponsive or completely fail.

** Static Sites are /Secure/
   #+cindex: vulnerabilities, websites
   #+cindex: website vulnerabilities
   With a static site, there is no database to breach and no server-side
   platform or CMS with unpatched vulnerabilities.  Static sites will not
   eliminate every vulnerability, but they narrow the window of opportunities
   available to any hacker and limit the amount of potential damage if a hacker
   does gain access.

** Other Benefits
   There are other benefits of static sites as well, including:

   #+cindex: flexible, benefit
   #+cindex: benefits, flexible
   - Flexibility ::
                    You are not working within a CMS framework, so there are no
                    limitations on how you can buidl your site.
     #+cindex: hosting, benefit
     #+cindex: benefits, hosting
   - Hosting ::
                Because there's no need for a database or server-side language
                support, hosting a static site can be anywhere from inexpensive
                to completely free, depending on your needs.
     #+cindex: versioning, benefit
     #+cindex: benefits, versioning
   - Versioning ::
                   Since a static site is made up of static files, it is
                   extremely easy to track and coordinate changes using version
                   control systems like Git and GitHub.


   #+cindex: static sites, what works
   With all of these benefits, why wouldn't you choose to use a static site?
   Well, only certain kinds of sites can realisticly work as static only.

** What Kind of Sites Can Go Static
   #+cindex: static sites, drawbacks
   #+cindex: drawbacks, static sites
   There are drawbacks to using static sites.

     #+cindex: dynamic data, drawback
     #+cindex: drawbacks, dynamic data
   - While some amount of dynamic data is possible on a static site that uses
     external API calls or third-party services, a static site is simply not
     suitable if you require large amounts of dynamic data or content
     personalization.
     #+cindex: learning curve, steep, drawback
     #+cindex: drawbacks, steep learning curve
   - From a development and content contribution standpoint, static site
     generators (i.e., the tools frequently used to build static sites) can
     have a steep learning curve.
     #+cindex: deployment, drawback
     #+cindex: drawbacks, complex deployment
   - Deployment can be complex, making static sites less than ideal for content
     that changes frequently.


   #+cindex: static sites,what works
   #+cindex: content focused, static sites
   #+cindex: user interaction, low, static sites
   Sites that tend to work best as static sites are content-focused,
   infrequently updated (once or twice a day at most), and do not require a
   high degree of user interaction or personalization.

   Here are some examples of types of sites that work well as static sites:

   #+cindex: blog, static site
   #+cindex: Disqus, service
   #+cindex: services, third party, Disqus
   - Blogs ::
              This is the most common use case; many static site generators
              default to a blog template.  Blogs are content-focused by design
              and, in many cases, user interaction is limited to comments,
              where services like [[https://disqus.com/][Disqus]] con fill the requirement.

** What Are Static Sites
   #+cindex: static site generators
   #+cindex: function, static site generator
   #+cindex: markup language
   #+cindex: static site generators, list of
   #+cindex: static site generators, data, metadata
   #+cindex: data, SSG's
   #+cindex: metadata, SSG's
   Static site generators solve the pain of building and maintaining a static
   site.  The fundamentals of a static site generator are extremely simple:
   they take in dynamic content and layout and output static HTML, CSS, and
   JavaScript files.  There are literally hundreds of static site generators
   <<static-site-generators>>([[https://staticsitegenerators.net/]]) but
   essentially they all do exactly the same thing and, for the most part,
   function similarly.

   - lightweight markup language (~Markdown .md~)
   - a templating language (~Handlebars {{}}~)
   - data/metadata (~Yaml .yml~)
   - CSS preprocessor (~Sass .scss~)
   - a compile-to-JavaScript language (~CoffeScript .coffee~)
   - \dArr
   - S S G \rArr ~.html .css .js~


   #+cindex: static site generators, in common
   {{{heading(What SSG's Have In Common)}}}
   - Templating language ::
        Use one or more, such as Liquid, Handlebars, Jade.  This is a key part
        of any static site generator, as it allows one to build a layout/theme
        for a site and plug in dynamic content during a build.
   - Markup language ::
        Use one or more ([[http://bit.ly/2lrz8JP]]) such as Markdown, AsciiDoc,
        reStructuredText.  Using a lightweight markup language makes it quicker
        and easier to write content using any text editor.
   - Command line ::
        Are run via the command line.
   - Local development server ::
        This allows you to develop and test locally befdore building and
        deploying your changes.  Typically, the tool watches the folder where
        the site files are being edited and recompiles the site on-the-fly as
        you edit them.
   - Extensible ::
        In most cases, if your static site generator doesn't support a feature
                   or language that you need, it has a build-in plugin
                   architecture that allows you to add that in (provided you
                   can code in the language the tool is built upon).
   - Support file-based data formats ::
        e.g. YAML, TOML, JSON.  File-based data allows you to structure any
        type of data independent of its display.


   #+cindex: static site generators, report
   #+begin_cartouche
   @@texinfo:@sansserif{@@The author has published a report called
   @@texinfo:@cite{@@Static Site Generators: Modern Tools for Static Web
   Development (O'Reilly 2015)@@texinfo:}@@.  The report focuses on the history
   of static sites, how they differ from dynamic sites built using content
   management systems or blog engines, and gives some details about the
   available static site generators.@@texinfo:}@@

   @@texinfo:@sansserif{@@The report is free and can be downloaded from
   O'Reilly here: [[http://oreil.ly/2l4fL8j]].@@texinfo:}@@
   #+end_cartouche

*** How to Choose a Static Site Generator
    #+cindex: static site generator, using
    So now with a basic understanding of what a static site generator is, how
    can one use them?  The first issue to resolve is trying to figure out which
    one to use.  This isn't an easy decision, since there are in excess of 445
    different available options.  ([[static-site-generators][List of SSG's]]). Even after filtering out
    projects that haven't been updated recently, there are still hundreds of
    potential tools.

    {{{subheading(How To Choose the Right SSG?)}}}
    #+cindex: static site generator, choosing
    #+attr_texinfo: :indic @i
   - The relative ``health'' of the project ::
        How recently has it been updated, and how big and active is the
        community?
   - How good is the documentation ::
        Many of the hundreds of static site generators (probably a majority)
        are not well documented.  This can cause you to spend far more time
        than necessary building your site and lead to needless frustration.
        Review the documentation carefully before committing to a project and
        don't assume that being able to read the source is sufficient.
   - Does it support my requirements ::
        This can involve very specific requirements (an importer or specific
        plugin) or a more general ability to meet amy needs (is it even
        extenible?).
   - Is the language it is built upon important to me ::
        For most, a static site generator will work well out of the box.  But
        in some cases it might be necessary to customize your generator via
        plugins or even contributions to the source code.  In these cases,
        knowing the underlying language can be important.


*** Going Forward
    The next chapters will look at some of the more mature and popular options
    for developing static sites, such as:
    - Jekyll (Ruby)
    - Hugo (Go)
    - Harp (JavaScript)


    Not only does each have a different underlying language, which may be an
    important consideration, but each also has its own pros and cons.  The
    chapters will look at building some common use cases:
    - a basic informational site
    - a blog
    - documentation site


    {{{noindent}}}using these tools in ways that take advantage of their
    relative merits.

    {{{heading(Dynamic Features)}}}
    Once the basics of the static site have been built, there needs to be added
    some dynamic features, like comments on a blog post, or a site search.  Or,
    if we have to support content contributors that aren't comfortable writing
    posts in Markdown via a text editor, we might want to add a CMS-like
    backend to the site to allow for easy editing.  The following will take a
    look at multiple solutions that solve each of these problems.

    {{{heading(Deployment)}}}
    After the site is complete, it's time to deploy it.  While this can be as
    easy as simply FTPing files onto a server, in most cases you'll want to
    automate the process or take advantage of services that can manage the
    build process for you.  The following chapters will explore a variety of
    tools and services that can ease the deployment process.

    {{{heading(Migration)}}}
    Finally, you may be evaluating static sites as an option to replace an
    existing site that uses a tool like WorkPress or some other CMS.  For these
    cases, the chapters will dive into tools that ease the process of migrating
    to a static site generator from a CMS by bringing over existing content.

    {{{heading(SSG Ecosystem)}}}
    In the end, this book hopes to provide you with a broad overview of the
    existing statit site generator ecosystem, while diving into the actual
    implementation details of how to accomplish your goals with these tools.

* Building a Basic Static Site

** Welcome to Harp

** Your First Harp Project

** Working With Layouts and Partials

** Working With Data

** Generating a Site

** Building Camden Grounds

** Going Further With Harp

* Building a Blog

** Blogging With Jekyll

** Your First Jekyll Project

** Writing a Post

** A Quick Introduction to Liquid

** Working With Layouts and Includes

** Adding Additional Files

** Working With Data

** Configuring Your Jekyll Site

** Generating a Site

** Building a Blog

** Going Further with Jekyll

* Building a Documentation Site

** Characteristics of a Documentation Site

** Choosing a Generator for Your Documentation Site

** Our Sample Documentation Site

** Creating the Site

*** Installing Hugo

*** Generating the Initial Site Files

*** Configuring the Hugo Site

*** Adding Content

*** Creating the Layout

** Going Further

* Adding Dynamic Elements

** Handling Forms

*** Wufoo Forms

*** Google Docs Forms

*** Formspree

*** Adding a Comment Form to Camden Grounds

** Adding Comments

*** Working with Disqus

*** Adding Comments to The Cat Blog

** Adding Search

*** Creating a Custom Search Engine

*** Adding a Custom Search Engine to a Real Site

** Even More Options

* Adding a CMS

** CloudCannon

*** Creating a Site on CloudCannon

*** Editing a Site on CloudCannon

*** Where to Go from Here

** Netlify CMS

*** Setting Up the Netlify CMS

*** Where to Go from Here

** Jekyll Admin

*** Setting Up Jekyll Admin

*** Editing a Site in Jekyll Admin

*** Where to Go from Here

** More Options

*** Forestry.io

*** Lektor

*** Headless CMS

* Deployment

** Plain Old Web Servers

** Cloud File Storage Providers

*** Hosting a Site on Amazon S3

*** Hosting a Site on Google Cloud Storage

** Deploying with Surge

** Deploying with Netlify

** Summary

* Mirgrating to a Static Site

** Migrating from WordPress to Jekyll

** Other Migration Options

*** Hugo

*** Middleman

*** Hexo

*** Harp

*** Many More Options Are Available

** Go Forth and Be Static

* Copying
  :PROPERTIES:
  :Copying:  t
  :END:
  Based upon /{{{title}}}/ by {{{author}}} & {{{subauthor}}} (O'Reilly).
  \copy 2017 {{{author}}}, 978-1-491-96094-3.

  This document was:

  Produced: {{{time(%F %R)}}}
  Version: {{{VERSION}}}
  Edition: {{{EDITION}}}
* Index
  :PROPERTIES:
  :Index:    t
  :END:
* Export Settings                                                  :noexport:
#+TEXINFO_PRINTED_TITLE: Outline of @i{Working With Static Sites}
#+TEXINFO_CLASS: info
#+TEXINFO_DIR_CATEGORY:WebDev
#+TEXINFO_DIR_TITLE:working-with-static-sites
#+TEXINFO_DIR_DESC:Outline of Working With Static Sites by R Campden & B Rinaldo
#+MACRO: subauthor Brian Rinaldo
#+MACRO: command @@texinfo:@command{*@@$1@@texinfo:*}@@
#+MACRO: samp @@texinfo:@samp{@@<$1>@@texinfo:}@@
#+MACRO: heading @@texinfo:@heading @@$1
#+MACRO: subheading @@texinfo:@subheading @@$1
#+MACRO: noindent @@texinfo:@noindent @@
